export default [
  {
    name: 'Arwen',
    age: '2',
    picture: 'http://lorempixel.com/400/400/cats/1',
    alt: 'what',
    url: 'lorem',
    id: 0,
  },
  {
    name: 'Bigotes',
    age: '4',
    picture: 'http://lorempixel.com/400/400/cats/2',
    alt: 'what',
    url: 'lorem',
    id: 1,
  },
  {
    name: 'Darth Vader',
    age: '0',
    picture: 'http://lorempixel.com/400/400/cats/3',
    alt: 'what',
    url: 'lorem',
    id: 2,
  },
  {
    name: 'Piruleta',
    age: '1',
    picture: 'http://lorempixel.com/400/400/cats/4',
    alt: 'what',
    url: 'lorem',
    id: 3,
  },
  {
    name: 'Arwen',
    age: '2',
    picture: 'http://lorempixel.com/400/400/cats/5',
    alt: 'what',
    url: 'lorem',
    id: 5,
  },
  {
    name: 'Bigotes',
    age: '4',
    picture: 'http://lorempixel.com/400/400/cats/6',
    alt: 'what',
    url: 'lorem',
    id: 6,
  },
  {
    name: 'Darth Vader',
    age: '0',
    picture: 'http://lorempixel.com/400/400/cats/7',
    alt: 'what',
    url: 'lorem',
    id: 7,
  },
  {
    name: 'Piruleta',
    age: '1',
    picture: 'http://lorempixel.com/400/400/cats/8',
    alt: 'what',
    url: 'lorem',
    id: 8,
  },
]
