pool:
  vmImage: 'macOS 10.13'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.1.0'
  displayName: 'Install Node'
- script: |
  yarn install
  yarn build
  yarn start:prod
  displayName: 'yarn install, build and start'
